### ISSUE TITLE
Agregar Buscador

### ISSUE THREAD

**Issue by eldelentes** [eldelentes/comoayudarmx#1]
Necesito ayuda para poder agregar un buscador o forma de filtrar las tarjetas de ayuda.

**Comment by vovimayhem** [comment]
Deja veo qué se me ocurre...

**Comment by vovimayhem** [comment]
#4

**Comment by bhserna** [comment]
Si quieres te puedo ayudar en algo que filtre ahi en el cliente las tarjetas... tal vez por ciudad? O que tenias pensado?

**Comment by hectormmg** [comment]
Yo también estaba pensando por ciudad, pero también podría ser por tipo de donación.

**Comment by eldelentes** [comment]
Lo mas importante es por "location" y por tipo de donativos.

El problema es que por el tipo de proyecto no existen categorías definidas, pensaba hacer algo bien simple con javascript pero aún no sé cuál seá la mejor manera...

**Comment by vovimayhem** [comment]
Si está cabrón pero ánimo... por lo pronto a moverse changuito

**Comment by bhserna** [comment]
Yo creo que eso es lo mejor por ahora...

**Comment by bhserna** [comment]
Deja trabajo en una propuesta y tu la revisas a ver sinte convence

**Comment by bhserna** [comment]
@eldelentes hice un pull request #14 ... es un filtro sencillo con el contenido que esta en el html. Creo que puede funcionar. Tal vez quieras revisar el diseño.

**Comment by eldelentes** [comment]
NVM Ya funciono, yo arrego el diseño @bhserna ¡Muchas gracias!

**Comment by hectormmg** [comment]
@eldelentes a mi si me funciona en la página

**Comment by vovimayhem** [comment]
@bhserna rockanroll dude! Saca la trompeta!!!!
