### ISSUE TITLE
Ya tengo un backend

### ISSUE THREAD

**Issue by jose-carrasco** [eldelentes/comoayudarmx#105]
Hola,

Ya tengo desarrollado un back-end: https://github.com/pptonio/donamexico

¿Quién me ayuda a integrarlo al front-end y así poder agilizar la carga de información?

**Comment by JPIglesias-Triangle** [comment]
Yo te podría ayudar en un par de horas.

**Comment by javarv87** [comment]
Excelente yo ayudo pero saldre hasta mañana por la mañna habi empezado algo con angular pero si alguien implemente algo mas pronto igual les apoyo
