### ISSUE TITLE
no cargan las tarjetas

### ISSUE THREAD

**Issue by elbaloo** [eldelentes/comoayudarmx#111]
![image](https://user-images.githubusercontent.com/1116842/30662227-3956bb0a-9dfb-11e7-989b-f635666696cf.png)

**Comment by lcolladotor** [comment]
<img width="677" alt="screen shot 2017-09-20 at 3 00 02 pm" src="https://user-images.githubusercontent.com/2288213/30662254-75896366-9e14-11e7-881d-e5f3c17cec94.png">

**Comment by elbaloo** [comment]
ya quedó con 45f75fa6b1ee57fbce8f0f90fd50b16dde2a90da
