### ISSUE TITLE
Herramienta de Mapeo

### ISSUE THREAD

**Issue by leodc** [eldelentes/comoayudarmx#116]
Hola ! con OSM México estamos haciendo un mapa para empezar a centralizar toda la información y además de dar al usuario herramientas para hacer reportes, te la comparto https://mapeo-colaborativo.herokuapp.com/ creemos que es importante empezar a levantar datos georreferenciados para un uso más sencillo, los datos quedan abiertos al público en la herramienta de carto (https://repubikla.carto.com/dataset/mapeo_comunitario) que piensan de que podamos agregar el mapa de reporte y consulta a su pagina? por ahora esta montado en un server y ustedes lo podrían jalar como un webview

**Comment by rafapprojects** [comment]
Hola que tal lo que estamos intentando centralizar informacion como la siguiente:
https://mapeo-crowdsourcing-sismo-19.herokuapp.com (es similar a lo que propones es la mism aplicacion de www.gob.mx)
puedes observar la pagina http://comoayudar.mx/voluntarios.html, creo que es buena idea utilizar sus herramientas. Conoces alguna forma de asegurar que la informacion se mantiene actualizada? 

Se plantea que en las proximas horas se trabaje con firebase de google como base de datos.

**Comment by leodc** [comment]
Ah jaja justo yo programe https://mapeo-crowdsourcing-sismo-19.herokuapp.com/, la situación con los datos que están ahí es que el proceso de actualización de los datos no deja automatizar para poder montar los datos en algún lado y compartirlos, pero los puedes descargar desde el github: https://github.com/mxabierto/crowdsourcing_sismo_19/tree/master/client/resources/data

La idea principal del desarrollo de https://mapeo-crowdsourcing-sismo-19.herokuapp.com/ era generar una herramienta de mapeo (su mismo nombre lo dice), sin embargo por necesidad tuvimos que enfocarnos en un mapa de consulta de los datos que ya se tenían en otras fuentes... pero igual creemos que es importante además de centralizar datos que ya existen generar una herramienta para centralizar y generar nuevos

**Comment by leodc** [comment]
Conocen CARTO ? ese es un muy buen lugar para empezar a centralizar datos, es una base de datos geográfica (postgis) en la nube, pueden checarla aquí: https://carto.com/ con otro proyecto que tengo https://repubikla.herokuapp.com/ somos ambassadors, si es necesario podemos darles las credenciales para hacer uso del servicio, tienen un api de sql para poder manejar los datos: https://carto.com/docs/carto-engine/sql-api/
