### ISSUE TITLE
Promocionar la pagina en redes sociales

### ISSUE THREAD

**Issue by rafapprojects** [eldelentes/comoayudarmx#118]
Con el fin de que llegue a mas gente la informacion es bueno reutilizar post en redes sociales y twittear constantemente la pagina de comoayudarmx.
Tambien hagan publicos sus mensajes solo para estas publicaciones

**Comment by skabbes** [comment]
Cloudfront hasn't propagated enough yet to finish the CSS, but I have added it to our homepage.

https://www.thinkbright.mx/
