### ISSUE TITLE
Twitter feed con hashtags relevantes

### ISSUE THREAD

**Issue by hectormmg** [eldelentes/comoayudarmx#12]
Me llegó la sugerencia de que listemos hashtags de twitter que puedan ayudar a la gente a encontrar información, pero además podríamos poner un feed de twitter que muestre tweets con esos hashtags.

**Comment by marino334** [comment]
Por que no poner una liga al twitter? Mejor direccionar algo del trafico a twitter en vez de tenerlo aqui
https://twitter.com/comoayudarmx

Edit: acabo de ver que esta' en "Acerca de", tal vez valga la pena poner un icono de twitter en la barra principal para ir directamente a el

**Comment by hectormmg** [comment]
De hecho ya hay varias ligas al twitter, pero sería buena idea agregar al menos la lista de hashtags que se están usando para que la gente se pueda informar

**Comment by RegulEsteban** [comment]
@HectorMg en la página de codeandomexico https://codeandomexico.github.io/terremoto-cdmx/ ya hay una lista de hashtags, estaría bien agregar la misma?

Usar Twitter de manera organizada y consciente.
Hashtag #sismo es para información general.
Hashtag #sismoCDMX y #sismoCDMX19sep17 para la ciudad de méxico.
Hashtag #ayuda o #ayudaciudadana para solicitar medicamentos, cosas, insumos, personas, etc.
Hashtag #sebusca para publicar información de personas en búsqueda.
Hashtag de ubicación #CDMX, #Puebla, #Morelos, #Cuernavaca, #Jojutla
Hashtag #RevisaMiGrieta para dudas sobre el estado de tu inmueble.

**Comment by hectormmg** [comment]
No veo porque no, que opinas @eldelentes?

**Comment by marino334** [comment]
Siento poner esto aqui pero no tengo twitter, alguien puede poner esto en el twitter de @ComoAyudarMX? Es un camion que acaba de salir desde CDMX hacia Cuernavaca (9/21 11:30pm), estaria bueno informar a quien mas lo necesite ahora que es de noche:
https://www.facebook.com/marino334/posts/10155379626788381

Gracias

**Comment by darthkrone** [comment]
hola ya hice algo parecido con una app en internet se puede agregar al proyecto
https://github.com/eldelentes/comoayudarmx/issues/265
