### ISSUE TITLE
Index.html o world.html no muestra las tarjetas

### ISSUE THREAD

**Issue by marino334** [eldelentes/comoayudarmx#122]
Parece que el contenido de cards.js no se esta' mostrando ni en la pagina de espaniol ni ingles

**Comment by marino334** [comment]
Veo que fue arreglado quitando una ";" en un cambio, la pagina sigue sin desplegar las tarjetas. Cada cuanto tiempo se sube el codigo "checked-in" al servidor? estaria Bueno darle prioridad a hacerlo ahora, dado que las tarjetas simplemente no se ven. @eldelentes

**Comment by marino334** [comment]
Verifique' que Cards.js ya fue actualizado en el servidor y las tarjetas siguen sin desplegarse correctamente, como se reactiva este Issue? hay que darle prioridad, dado que nadie las puede ver @eldelentes

**Comment by eldelentes** [comment]
@marino334 Efectivamente suele ser por un error de sintaxys en `cards.js`, si vuelve a pasar corrobora que ese archivo no tenga `;` o dobles comas.

**Comment by marino334** [comment]
Cheque' que no haya ";" Lo major seria tener algun tipo de verificador del archivo, como parte de hacer check-in, no he usado GitHub, no se si sea posible hacer algo asi y evitar estas molestias para todos
