### ISSUE TITLE
Feature: Abrir el reporteo al público

### ISSUE THREAD

**Issue by saul-mtz** [eldelentes/comoayudarmx#126]
**Descripción:**
- Crear un formulario público para que cualquier persona pueda agregar/modificar "cards".
- Para evitar el troleo autenticarse a través de Facebook debe ser obligatorio.
- Cuando se hace una nueva publicación es obligatorio especificar Estado/Colonia y mostrar lo existente de acuerdo a esos filtros para evitar duplicados.
- También es posible reportar información ya publicada que es falsa u obsoleta.
- La información reportada entra a una lista de moderación que alguien del equipo de comoayudarmx debe aprobar.

**Propuesta de integración:**
- Usar Firebase: #78 
- Usar [Firebase Auth](https://firebase.google.com/docs/auth/?hl=es-419) y [Firebase UI](https://opensource.google.com/projects/firebaseui).
- Usar el [listado de colonias de Sepomex](http://www.sepomex.gob.mx/lservicios/servicios/CodigoPostal_Exportar.aspx).

**Comment by rafapprojects** [comment]
Hay que tomar en cuenta la parte geografica #46  #83  #116

**Comment by eldelentes** [comment]
Unirse a información de backend #36
