### ISSUE TITLE
AppAndroid

### ISSUE THREAD

**Issue by shingrey** [eldelentes/comoayudarmx#137]
Hola chicos estoy trabajando en una app android, el primer punto a sacar son las card
actualmente estoy tomando card.js para obtener la información , si se crea el backend actualizare la app para que baje esa info.

un saludo

**Comment by kiramishima** [comment]
Hola acaban de publicar una la gente de Androidtitlan , estaría bien que se agregara una sección más a esa app tomando los datos de las cards de aquí.
https://play.google.com/store/apps/details?id=io.github.erikcaffrey.ayudamexico

**Comment by eldelentes** [comment]
Así es, por ahorita la app queda fuera de este desarrollo, ya se esta trabajando en un back end. Re recomiendo unirte al proyecto de Ayuda México
