### ISSUE TITLE
¿Necesitan ayuda?

### ISSUE THREAD

**Issue by miguelsalazar** [eldelentes/comoayudarmx#138]
En el Slack de Codeando México hay un buen de developers que están buscando cómo colaborar. Revisé los issues y se ve que tienen todo bajo control, pero cualquier cosa, échenos un grito. O bien, únanse en http://slack.codeandomexico.org y desde ahí también pueden pedir ayuda con issues.

**Comment by genitalico** [comment]
@miguelsalazar armamos una organizacion aqui https://github.com/ComoAyudarMX
 Junto con https://github.com/orgs/ComoAyudarMX/people/dannegm

para empezar a implementar algunas, de momento estamos armando un back para poder alamcenar, agregar y buscar informacion
