### ISSUE TITLE
Elementos de nav desaparecen en mòbil

### ISSUE THREAD

**Issue by polkduran** [eldelentes/comoayudarmx#143]
En una pantalla de tamano reducido (como en un mòbil) ciertos elementos de navigaciòn desaparecen dejando solo "Acerca de" y "English", entonces no se puede acceder a "Contactos" y "Voluntarios".
En un browser probar reduciendo la ventana.
Lo siento no soy bueno en css para poder corregirlo.
![image](https://user-images.githubusercontent.com/4704913/30670149-82030de8-9e61-11e7-9074-c1173f127af0.png)

**Comment by ghostlyRvn** [comment]
tienen un class .hide-mobile  que les cambia el display.

Ayuda para no llenar el espacio en móviles. Habría que evaluar cuales elementos sí son importantes para mantener en el nav de movil y cuales mantener ocultos.

**Comment by eldelentes** [comment]
Cómo comenta @valenc3x lo hicimos a proposito para poder tener un sitio responsivo de manera rápida. Habría que evaluar crear un menu responsivo.

**Comment by marcxploit** [comment]
Hola, sin problemas puedo hacer el menú que necesitan pero necesito saber como hacérselos llegar. Saludos.

**Comment by eldelentes** [comment]
@marcxploit ¿Estas familiarizado con los FORK y PR?

**Comment by enriquegarga** [comment]
Qué tal, les puedo echar la mano con el menú responsive, de hecho está casi listo, ¿hago PR?

**Comment by eldelentes** [comment]
Por favor @enriquegarga

**Comment by hectormmg** [comment]
Resuelto #165
