### ISSUE TITLE
Bot Twitter

### ISSUE THREAD

**Issue by eldelentes** [eldelentes/comoayudarmx#149]
Buscamos implementar el siguiente bot en algun server, puede ser Heroku. Esto para ayudar a nuestra cuenta de Twitter

https://github.com/Garyi/Filtro-Informaci-n-Valiosa-Terremoto-Twitter/tree/master

Si alguien se anima comente y le envio las credenciales...

Las palabras que nosotros tenemos que buscar son:
```
#busco
#tengo

```

**Comment by kiramishima** [comment]
Yo estoy creando uno para la plataforma de Facebook que tome los datos de card.js
ahorita estoy lidiando con el hecho de que hay una variable dentro de ese js file jaja

**Comment by Cacilie** [comment]
He modificado el ReadMe para que sea más claro 👯‍♂️  También les recuerdo que el script se puede estar corriendo en una computadora. Y es importante configurar "ya sea computadora o servidor" cada cuanto se ejecuta el script

**Comment by eldelentes** [comment]
Podria ejecutarlo en un mi computadora pero me interesa mas automatizarlo para no depender de que yo este disponible...

**Comment by kodamirmo** [comment]
Yo lo subo a un server.

**Comment by Cacilie** [comment]
Acabo de hacer un commit, nada más moví unas cosas. Sólo les recuerdo que el bot está programado para #AyudaCMX, para ponerlo con el que ustedes deseen nadamás hace falta cambiar una linea. En el Readme especifico cual es :D 

También recuerden que hay que configurar su ejecución :D para que se ejecute cada que usted quiera. En linux se puede con CRON.

**Comment by kodamirmo** [comment]
Oye @Garyi en el README dice que para cambiar el hashtag es en una linea que no hay nada, donde es?

**Comment by Cacilie** [comment]
Perdón, con las modificaciones se cambió a la linea 31 🌵  una disculpa, modificaré pronto el READMe para evitar confusiones.
![image](https://user-images.githubusercontent.com/14913081/30673199-fdc540e8-9e36-11e7-9399-4f55d0313b9b.png)

**Comment by digenz** [comment]
Yo tengo un shared hosting en https://www.tmdhosting.com/ el que dice cloud sites..  totalmente disponible por mas o menos 6 meses.  si les sirve lo pueden usar.  yo no lo se configurar pero les paso los logins 
( no tiene nada.. es nuevo)

**Comment by eldelentes** [comment]
Solcuionado gracias a @kodamirmo
