### ISSUE TITLE
Google Forms + Google Spreadsheets para concentrar información

### ISSUE THREAD

**Issue by aalkz** [eldelentes/comoayudarmx#160]
Hola, en lo que queda algún tipo de backend más robusto, propuse una forma de concentrar la información mediante Google Forms y Google Spreadsheets, ya le di acceso a comoayudarmx@gmail.com, si se necesita para alguien más díganme por favor.

La form: https://docs.google.com/forms/d/e/1FAIpQLSf_kylBvkVQXaJmBAILdpjKCsl6lERlhtnhFfB1_22g43sz4g/viewform

El PR con los commits donde ya está en el botón de publicar el link a esta form: 
https://github.com/eldelentes/comoayudarmx/pull/158

Se aceptan sugerencias, adiciones, comentarios, etc.

**Comment by Mackaber** [comment]
Si se implementa esta idea se puede usar algo así --> https://coderwall.com/p/duapqq/use-a-google-spreadsheet-as-your-json-backend para pasarlo directo a las tarjetas, yo he implementado algunas cosas para leer y escribir con Google Sheets avísenme si necesitan mi ayuda...

**Comment by bhserna** [comment]
@aalkz ya esta en master #158
