### ISSUE TITLE
Agregando Centros de acopio para Querétaro

### ISSUE THREAD

**Issue by leonelMendoza** [eldelentes/comoayudarmx#161]
Hola, estaré recopilando centro de acopio para Querétaro.

**Comment by chefest** [comment]
Centros de acopio en Querétaro.
![21687961_1761259834178871_979679194329675089_n](https://user-images.githubusercontent.com/7718211/30674000-ad26895c-9e3c-11e7-8c1a-bf5a11c231c9.jpg)

**Comment by chefest** [comment]
Probable URL para centros de acopio de queretaro:
https://www.google.com/maps/d/u/0/viewer?mid=1JgclXGgsN4Nc8Oz5LiZuPiXh8RY&ll=20.57823999618151%2C-100.39123335&z=14

**Comment by javarv87** [comment]
Ya hice un PR con la información de la imagen y el mapa agregado, esperemos se apruebe, Saludos, ustedes están en Qro, podríamos organizar algo también estoy en Qro saludos??

**Comment by hectormmg** [comment]
Cerraré este issue ya que tenemos el PR #174 de @javarv87 en espera, una vez que terminemos la limpieza de las tarjetas existentes lo incorporamos :D, gracias!
