### ISSUE TITLE
Comunicación entre colaboradores

### ISSUE THREAD

**Issue by Mackaber** [eldelentes/comoayudarmx#162]
Hola, sugiero usar alguna plataforma como https://gitter.im/, Slack, Discord, etc... para llevar a cabo la comunicación en especial para los que están trabajando con un mismo issue...

**Comment by ortegaguillermo** [comment]
tengo discord, telegram, hangouts, en cuanto salga del trabajo busco los issues para ver si pongo un api en json aunque sea abierta

**Comment by kiramishima** [comment]
se puede usar el Slack de codeando, pero abran un canal para este repositorio, siento que los canales se saturaron con todos los proyectos :/

**Comment by aalkz** [comment]
Creo que esta discusión ya está en #55
