### ISSUE TITLE
links paea donar en espanol

### ISSUE THREAD

**Issue by luzcerv** [eldelentes/comoayudarmx#167]
Hola,
Es super util tener la pagina en ingles pero luego al picar 'more information' para la Cruz roja y otros solo sale informacion en español. Nadie que no hable español podra donar por ahi. Como se puede solucionar? Alguien que tenga contacto en la cruz roja para que les apoyemos para tener la informacion en ingles? O hay algun enlace en ingles que se pueda meter en vez de ese?

Con gusto ayudo con traducciones. 

Mucha fuerza!

**Comment by CronGM** [comment]
Aquí hay algunos enlaces con páginas en inglés. ¿Quizás alguien podría convertirlos en tarjetas, si no están ya disponibles?

http://fortune.com/2017/09/20/earthquake-in-mexico-donations-help/

**Comment by eldelentes** [comment]
@CronGM De hecho esa sería la solución más optima.

**Comment by arturojain** [comment]
¿y si usamos las traducciones de Google Translate como links en inglés? i.e. https://translate.google.com/translate?sl=es&tl=en&u=[url]

**Comment by munick** [comment]
@arturojain parece que recaptcha no sirve con google translate: [https://translate.google.com/translate?sl=es&tl=en&u=cruzrojadonaciones.org](https://translate.google.com/translate?sl=es&tl=en&u=cruzrojadonaciones.org)

**Comment by miguejs** [comment]
Voy a cerrrar este issue, lo mejor seria implementar la solucion de @CronGM

**Comment by arturojain** [comment]
#194
