### ISSUE TITLE
PWA(Progressive web app) ServiceWorkers para ver que se puede trabajar offline

### ISSUE THREAD

**Issue by javarv87** [eldelentes/comoayudarmx#181]
Ya estoy trabajando algo de esto

**Comment by hectormmg** [comment]
@javarv87  puedes elaborar en la descripción porfavor? Estamos limitando mucho el scope de los issues para dirigir todo el esfuerzo a lo urgente y puede que no sea tan relevante.

**Comment by javarv87** [comment]
Claro estoy usando service workers para trabajar con la información relevante como las tarjetas, que puedan leerse offline.
