### ISSUE TITLE
Contactos? 

### ISSUE THREAD

**Issue by vovimayhem** [eldelentes/comoayudarmx#2]
* Protección Civil?
* Locatel?

**Comment by eldelentes** [comment]
@vovimayhem Buena idea podríamos agregar una página con esa información http://comoayudar.mx/contactos.

**Comment by hectormmg** [comment]
Si quieren me puedo aventar esa página, ¿utilizo la misma estructura de las tarjetas para donativos?

**Comment by eldelentes** [comment]
@HectorMg Si Hector!

**Comment by hectormmg** [comment]
Perfecto, en eso ando

**Comment by hectormmg** [comment]
Ya agregué la página con alguna información en el PR #10
