### ISSUE TITLE
Add cards Centro Horizontal, Fundación Checo Pérez

### ISSUE THREAD

**Issue by jorandradefig** [eldelentes/comoayudarmx#206]
Assignee: @jorandradefig.

**Comment by jorandradefig** [comment]
Issue completado en PR #205.

**Comment by miguejs** [comment]
Usar el formulario para agregar nuevos cards: https://docs.google.com/forms/d/e/1FAIpQLSf_kylBvkVQXaJmBAILdpjKCsl6lERlhtnhFfB1_22g43sz4g/viewform
