### ISSUE TITLE
ELIMINAR Donación topos.mx de la lista 

### ISSUE THREAD

**Issue by albarron** [eldelentes/comoayudarmx#208]
Hola,

de acuerdo con el auténtico dirigente del grupo topos, la cuenta de donación señalada es falsa. 
Aquí un video a la entrevista por Aristegui: http://m.aristeguinoticias.com/2009/mexico/topos-no-estan-pidiendo-dinero-representante-video/

Dado que esta página se ha vuelto una referencia, urge elimiarlos (o mejor aún, marcarlos como fraudulentos)

Saludos

**Comment by jorandradefig** [comment]
Los 'topos' de la nota son los Topos Azteca. Quienes reciben donaciones son los Topos Tlatelolco.

Saludos

**Comment by albarron** [comment]
exacto. Mira el video que enlazo por favor: el representante de Topos Azteca denuncia que la organización Topos Tlatelolco es falsa. Presume que se trata de una persona que lucra y no destina las donaciones a la ayuda necesaria

**Comment by polkduran** [comment]
Pues si parece una historia complicada porque en otro video Aristegui dice otra cosa (sobre los topos de Tlatelolco).

https://aristeguinoticias.com/2009/mexico/otro-representante-de-topos-dice-que-si-requieren-ayuda-economica-video/

**Comment by albarron** [comment]
¡Qué complicado! Intentaré investigar un poco más. Quizás alguien más puede indagar algo

**Comment by juliescript** [comment]
Aquí la historia de los dos grupos de Topos. Aparentemente hay varios grupos pero todos con el mismo fin. https://www.facebook.com/notes/brigada-de-rescate-topos-tlaltelolco-ac/breve-historia-de-los-topos/1671963289480489/ pero aún así, espero más confirmaciones por otros devs. Varias fuentes dicen que sí son reales. En lo personal, yo decido confiar.

**Comment by albarron** [comment]
Gracias por el enlace. La realidad es que esa historia la cuentan ellos mismos y la publican con fecha de hoy. Con el RFC que mencionan en ese mismo documento hice una búsqueda y encontré dos enlaces:

- www.sat.gob.mx/informacion_fiscal/normatividad/Documents/anexos_RMF2016_parte2.doc
Un extracto del diario oficial donde aparece su registro

- www.sat.gob.mx/terceros_autorizados/donatarias_donaciones/Documents/DA_incumplimientoTransparencia.xls
Un extracto del SAT en el que aparecen como "Autorizaciones que pierden vigencia por el incumplimiento de la obligación correspondiente al ejercicio fiscal 2012 [...] Información para garantizar la transparencia, así como el uso y destino de los donativos recibidos"

Independientemente de que es discutible que el SAT publique documentos en doc y en xls (¡y el segundo está fechado en 2018!), esto no hace más que confundir aún más: cualquiera puede obtener un RFC. Ello no implica que destinen los recursos a la causa que mencionan. 

Coincido en que cada quien debe decidir si confiar o no. Ojalá mis sospechas sean falsas y de verdad estén usando los recursos obtenidos para ayudar.

**Comment by Tecayehuatl** [comment]
Hasta donde se sabe, topos no andaba pidiendo efectivo como ciudadano de a pie, sin embargo las donaciones (cuentas bancarias en su sitio) si son aceptadas, solo ayer en la entrevista que le hicieron a un integrante de topos que había alguien pidiendo dinero haciéndose pasar por el, pero que en realidad si necesitan ayuda. Incluso si hay dudas, puedes echar una llamada los correspondientes difusores de las noticias, los datos que aparecen en topos.mx son los mismo que en topos.red

**Comment by lmauromb** [comment]
En el Twitter oficial viene esta cuenta
https://twitter.com/topos/status/908000616575680512

**Comment by miguejs** [comment]
La información ha fue confirmada
