### ISSUE TITLE
Ajustar links de donación Cruz Roja en página en Inglés

### ISSUE THREAD

**Issue by juliescript** [eldelentes/comoayudarmx#209]
Estoy pidiendo donaciones usando la página en inglés en referencia (estoy en Alemania y pedí donaciones en mi empresa). Sin embargo, la página de PayPal aparece como 404 para los usuarios alemanes y me gustaría cambiar el link actual por este: https://www.paypal.me/cruzrojamexicana

**Comment by eldelentes** [comment]
Corregio , gracias.
