### ISSUE TITLE
Diseño

### ISSUE THREAD

**Issue by JPIglesias-Triangle** [eldelentes/comoayudarmx#210]
Estaba checando y vi que cuando crecen las cards todo se mueve. Se me ocurrió que podríamos usar algo como Masonry JS, para que se mantuviera un orden.

**No me parece tan importante ahorita, pero sería bueno implementarlo a futuro.**

**Comment by eldelentes** [comment]
Ya estamos cambiando el diseño,  no agregamos masonry o algo similar para no alentar el sitio o tener más librerias que cargar. Pero estamos solucionando eso.
