### ISSUE TITLE
Crear un bot para eliminar tweets

### ISSUE THREAD

**Issue by StrayChild01** [eldelentes/comoayudarmx#261]
Hola.

Se necesita un bot que elimine los tweets que tengan un tiempo de publicación mayor a 2 horas**.

**Debido a la naturaleza de la cuenta de twitter, el flujo de información cambia rápidamente. Entonces, al cabo de cierto tiempo se empieza a volver obsoleto y la gente contesta o da RT a cosas que ya no son necesarias, o que ya no se requieren, causando más ruido dentro del TL.

**Comment by luispeerez** [comment]
Creo que tendria que haber un moderador, puede que tweets que hayan tenido mas de esas 2hrs puedan seguir siendo utiles

**Comment by darthkrone** [comment]
intentare buscar algun bot, o tal vez con la misma API de twitter, o porque no contactando a TWITTER mismo y explicandole el asunto puedan ayudarnos como los de twinesocial

**Comment by ManuNovas** [comment]
Propongo que los que suban información proveniente de twitter propongan una dirección de correo electrónico para que cuando pasen 2 horas, se envíe un aviso para confirmar que se elimine el tweet o se mantenga en la plataforma

**Comment by StrayChild01** [comment]
Esto ya no se va a hacer.
