### ISSUE TITLE
Usar algún recortador de URL

### ISSUE THREAD

**Issue by StrayChild01** [eldelentes/comoayudarmx#262]
Hola.

Acabo de notar que cuando uno copia alguna de las URLs del sitio y se pegan en twitter, las URL se cortan:

![Error](https://user-images.githubusercontent.com/18584930/30767775-7ff1ed48-9fc5-11e7-9fdc-80a27ec05b3c.png)

Entonces, al dar click, manda al sitio principal y no al la sección que debería ser.

**Comment by darthkrone** [comment]
https://goo.gl/

**Comment by arturojain** [comment]
Este issue ya fue resuelto.
