### ISSUE TITLE
Se duplican registros iguales de Locación

### ISSUE THREAD

**Issue by aalkz** [eldelentes/comoayudarmx#263]
No sé qué sea pero probablemente porque se toman los de la fuente cards.js y después los del doc de Google?

![image](https://user-images.githubusercontent.com/6750582/30768244-67687b98-9fca-11e7-98bc-24e7b7f50271.png)

**Comment by enriquegarga** [comment]
Lo he notado, también aparece duplicado Estado de México. En San Luis Potosí hay dos centros de acopio iguales, y cuando llené el formulario para crear otro centro en San Luis no se reflejó en el sitio.

**Comment by arturojain** [comment]
Si encuentran información duplicada es de mucha ayuda informar, se hace un filtro de comprobación manual de toda la información, en cuanto a la duplicación de regiones se está trabajando en una solución

**Comment by josueadelima** [comment]
Los estados se están duplicando por disparidades en el campo `"gsx$puedesayudardesde":` por ejemplo, la duplicidad en Estado de México es porque dos de los campos México viene con acento y  uno más viene escrito como Estado de Mexico, otros es porque vienen con espacios antes o después de la cadena de texto. Lo ideal es que exista una lista de estados o locaciones y que ésta este ligada a la lista principal a través de un id, de igual forma el formulario para mandar información debería de ser un select y no un input.

Pensando en que de momento esta como texto y existe la premura, recomiendo que  antes de hacer el filtrado de estados, realicen un trim de espacios al comienzo y al final y quiten acentos para evitar en la medida de lo posible los duplicados en la lista.

**Comment by aalkz** [comment]
Ya estuve probando y sí es lo que dice @josueadelima , ya arreglé el duplicado de CDMX por ejempo, había unos campos que tenían `CDMX` y otros `CDMX ` (con un espacio al final).

![image](https://user-images.githubusercontent.com/6750582/30771414-18d7fede-a00d-11e7-8efd-1fe012c72cf6.png)

**Comment by miguejs** [comment]
@aalkz  Ya quedó solucionado este issue ?

**Comment by aalkz** [comment]
@miguejs en idea y proceso sí: hay que fijarnos que no haya duplicados en los datos, si quieres mejor lo cerramos y pensamos en una solución a largo plazo como la que dice @josueadelima . Cerrando!
