### ISSUE TITLE
Twitter feed con filtros de hashtags #BrigadaCAMX

### ISSUE THREAD

**Issue by darthkrone** [eldelentes/comoayudarmx#265]
https://www.twinesocial.com/comoayudarmx

http://recordit.co/a6P9QH735K

![brigada_01](https://user-images.githubusercontent.com/4318417/30771159-66e95246-a006-11e7-80fb-430ce1724104.jpg)
![brigada_02](https://user-images.githubusercontent.com/4318417/30771162-6e06fba0-a006-11e7-9952-0d5822f1970c.jpg)

**Comment by luispeerez** [comment]
No entiendo muy bien esto, necesitariamos el enlace de https://www.twinesocial.com/comoayudarmx en comoayudar.mx ?

**Comment by darthkrone** [comment]
NO, es una app se puede embeder dentro de comoayudar.mx en otra seccion como los mapas de google maps solo que por la urgencia del tiempo pongo el link directamente para los de la brigadaCAMX

<script id="twine-script" src="//apps.twinesocial.com/embed?app=comoayudarmx&showNav=yes"></script>

**Comment by luispeerez** [comment]
Ok, lo voy a agregar al menu como "tweets" y a embeber el script que me pasaste. Gracias

**Comment by luispeerez** [comment]
#278

**Comment by luispeerez** [comment]
@eldelentes @miguejs Avisenme si esta bien embeber el script que paso @darthkrone en esa seccion. Gracias

**Comment by darthkrone** [comment]
ok , de hecho estoy viendo todo ello porke una funcion que es REAL TIME y es para que los tweets aparescan en tiempo real es de pago, si no lo se actualizan cada hora y no seria muy funcional en ese caso, aunque si es de ayuda yo ya lo comprobe, por eso aun no la metia dentro del sitio pero si ya esta estupendo, ACABO de mandarle unos mensajes a la gente de twinesocial.com explicando de que va el asunto y si nos pudieran ayudar habilitando esa funcion gratis durante unos dias dada la emergencia para no perder tiempo construyendo una app parecida, asi que hora solo rsta ver que me dicen pero creo regresan hasta el lunes a laborar :( , asi que estaba viendo si alguien podria patrocinar el pagar la funcion de REAL TIME que cuesta $250 al dia (si yo tambien me fui de espaldas) pero si alguien lo paga 2 dias seria de mucha ayuda para los de #BrigadaCAMX osea toda la gente que busca canalizar a la gente atraves de los #hashtags #necesitamos-#tenemos 
https://paper.dropbox.com/doc/BrigadaCAMX-cgRhSXHMQoMnUMsnwwn2g

estare pendiente a ese asunto de mientras solo queda ayudar al diseño responsivo del sitio y con cosas pequeñas que pueda ayudar, saludos gente

**Comment by luispeerez** [comment]
Yo lo patrocino, solo diganme como hacer el pago.

**Comment by luispeerez** [comment]
@darthkrone Sabes como esta lo del pago de $250? vi en su pagina estos precios, tambien veo que tiene un trial de 30 dias
![screenshot from 2017-09-23 20 44 04](https://user-images.githubusercontent.com/3952671/30778628-0ee257f6-a0a0-11e7-85f6-8d3aeed95221.png)

**Comment by darthkrone** [comment]
si el trial es lo que esta ahora si kieres hablamos y nos ponemos de acuerdo tienes skype? es gratis la llamda creo no o discord avisame

**Comment by luispeerez** [comment]
@miguejs @eldelentes Hola, yo y @darthkrone  estamos configurando un nuevo widget para que tenga los tweets en tiempo real, ya que al parecer a las 7hrs, el widget empieza a jalar updates por hora, y no en tiempo real. Asi que si pudieran estar al pendientes para cuando suba el pull request y podamos poner el widget con los updates en tiempo real, esperamos tenerlo en unos 30min aprox.

**Comment by miguejs** [comment]
@luispeerez  Voy a estar al pendiente.

**Comment by luispeerez** [comment]
Todavía está pendiente esto, estaba pensando si esto no es realtime creo que podríamos quitarlo y poner un enlace al Twitter oficial, en lo que vemos una forma de desplegar tweets al instante. @miguejs @eldelentes

**Comment by luispeerez** [comment]
Hola buen día, buenas noticias, los de twinesocial activaron las actualizaciones realtime por una semana, solo habría que verificar con @darthkrone que tiene acceso al admin

**Comment by luispeerez** [comment]
![screenshot from 2017-09-24 09 27 58](https://user-images.githubusercontent.com/3952671/30783571-adbae220-a10a-11e7-999d-ee9af2ff903d.png)

**Comment by darthkrone** [comment]
hola k bueno ahora lo cheko

**Comment by luispeerez** [comment]
Lo que veo es que todavía no está actualizando en tiempo real, ya les mandé mail, no se si podríamos desactivar la sección en lo que nos ayudan con eso

**Comment by luispeerez** [comment]
Hola @miguejs @darthkrone @eldelentes ya estamos contactandonos con Twinesocial pero todavia no hay updates en tiempo real, acabo de hacer un pull request para enlazar mejor la cuenta de twitter.

**Comment by luispeerez** [comment]
#284

**Comment by luispeerez** [comment]
Que tal, disculpen por tanto va y ven pero ahora ya se estan actualizando los tweets en tiempo real asi que omitan el pull request 284, creo que cambiariamos hasta que expiren los 5 dias de real time updates que nos dieron. @darthkrone creo un issue sobre eso https://github.com/eldelentes/comoayudarmx/issues/281

**Comment by eldelentes** [comment]
@luispeerez No te preocupes Luis, gracias por la ayuda.
