### ISSUE TITLE
Widget-TwineSocial | Campaña #BrigadaCAMX

### ISSUE THREAD

**Issue by darthkrone** [eldelentes/comoayudarmx#281]
Aqui pondre como utlizar y actualizar el widget de _TwineSocial.com_ para tener en tiempo real los #hashtags de la gente y asi la gente de la #BrigadaCAMX y demas gente puedan hacer su trabajo mas rapido, que es reunir personas personas dadas sus situaciones necesidad-beneficencia **#necesitamos** / **#necesito** / **#tenemos** / **#tengo**. incluido otros como **#Voluntarix** para los voluntarios.
#BrigadaCAMX
https://paper.dropbox.com/doc/BrigadaCAMX-cgRhSXHMQoMnUMsnwwn2g
_Es importante estar atento a los cambios en esta direcccion para actualizar la app(filtros y colecciones) segun lo que necesite saber los miembros de la #BrigadaCAMX_

**Comment by darthkrone** [comment]
Hola @eldelentes y demas miembros hemos recibido contacto con el presidente de TwineSocial "Mark" y nos apoyara 5 dias gratis con el REALTIME debemos aprovecharlo ya que es una gran herramienta para ayudar, gracias a **@luispeerez** por su AYUDA, el y yo administraremos la app y la seccion de tweets, pero para QUE FUNCIONE NECESITAMOS GENTE #BRIGADISTA que una a las personas mientras admi la herramienta, si no NO habra valido la pena conseguir el real time, saludos @d4rthkrone

**Comment by darthkrone** [comment]
LA PLATAFORMA YA FUNCIONA TOTALMENTE, SI PUDIERAN PROMOCIONARLA PARA QUE MAS GENTE LA USE GRACIAS @eldelentes @luispeerez 
http://comoayudar.mx/tweets.html

**Comment by luispeerez** [comment]
Que tal a todos, buenas noticias. Me contactaron los de Twine social y habilitaron las actualizaciones del widget en real time por tiempo indefinido.

De cualquier forma voy a empezar a trabajar en un prototipo similar que pueda ayudar a otras cuentas de twitter para no depender completamente del widget -> https://github.com/luispeerez/comoayudarmxfeed
![2017-09-26-10-36-mail google com](https://user-images.githubusercontent.com/3952671/30869391-96e3fdbe-a2a6-11e7-85ab-8b8c63ed79b4.png)

**Comment by eldelentes** [comment]
@luispeerez Wow, súper, es increible que todo el proyecto (Menos el dominio) no ha costado nada de dinero. Gracias Luis, haz un PR agregandote en el `readme`

**Comment by luispeerez** [comment]
Todo el config del widget lo ha realizado @darthkrone igual lo agrego al readme

**Comment by darthkrone** [comment]
que buena noticia ami tambien me llegaron los correos pero yo sigo trabajando administrando la app de hecho MARK el presidente con el quien he estado hablando en estos dias se han mostrado muy entusiasta por ayudarnos creo que deberiamos al menos darles las gracias por tweet no creen? y ademas he estado uniendo gente ha sido una gran plataforma para ayudar ojala hubiera mas gente ayudando en las #brigadasCAMX @eldelentes, por cierto me llamo Gabriel Rios vivo en DF saludos y a seguir trabajando por **nuestro pais**, acabo de agregar al feed la cuenta de @MascotasSismo para ayudar a la busqueda de animales extraviados
![twinesoacil_mark1](https://user-images.githubusercontent.com/4318417/30891396-c92297c0-a2f8-11e7-8376-c970f436cccd.jpg)
![twinesoacil_mark2](https://user-images.githubusercontent.com/4318417/30891397-c9243ae4-a2f8-11e7-91fa-d5f182e3d92f.jpg)

**Comment by luispeerez** [comment]
Listo el PR #294
