### ISSUE TITLE
Traducción de Sitio

### ISSUE THREAD

**Issue by eldelentes** [eldelentes/comoayudarmx#31]
Una persona me dio la idea de traducir el sitio web para personas de todo el mundo...

**Comment by alfrobinson** [comment]
Yo puedo ayudar con el PHP para la geolocalización, si es que es de utilidad.

**Comment by eldelentes** [comment]
@alfrobinson En #36 se esta hablando del tema del back end. Por lo pronto sería de buscar la forma más rápida y no conflictiva de hacerlo. Si PHP puede ayudar no hay problema.

Sin embargo ahorita el sitio esta creado con HTML Y CSS para utilizar Github Pages como hosting y CMS, por lo tanto al cambiar a PHP necesitamos subirlo a un sitio etc.

Espero tus comentarios e ideas...

**Comment by IsabelPalomar** [comment]
Yo puedo apoyar con la traduccion @eldelentes, lo que desconozco es como seria la logica para cambiar entre el js que se estra mostrando actualmente.

**Comment by eldelentes** [comment]
Podriamos utilizar alguna libreria que exista por ahí. En realidad lo importante no es tradución los textos de descripción si no el contenido general, como botones, introducciones, etc...

**Comment by IsabelPalomar** [comment]
Crees que esta pueda funcionar @eldelentes http://i18njs.com/?

**Comment by eldelentes** [comment]
Si de hecho que tenga un json separado me agrada mucho, creo que peude funcionar muy bien, igual, hay un PR #38 que busca agregar Angular al sitio, también es algo a considerar...

**Comment by GregMBS** [comment]
PHP/MySQL y Inglés nativo. Como puedo ayudar?

**Comment by bhserna** [comment]
Para cambiar el lenguaje, yo me imagino que sea con un select en la parte superior derecha.

Y para técnicamente como realizar el cambio, yo veo las siguientes opciones:

## Escribir texto al inicializar

Podemos tener una carpeta `locales` donde podamos en cada una meter un objeto con las traducciones. Ej:

```js
# locales/es.js

es: {
  about: "Acerca de",
  emergency_contacts: "Contactos de emergencia"
  ....
}
```

```js
# locales/en.js

en: {
  about: "About",
  emergency_contacts: "Emergency contacts"
  ....
}
```

Y usando algún tipo de atributo en tag de html ya sea un id o tal vez sea mejor un "data attribute" como `<span data-i18n="about"></span>` podríamos sustituir todas las llaves que encontremos al inicializar el documento.

## Usar procesador de sitios estáticos

Otra opción que tal vez sea más formal, pero hace más complicado el proyecto por que le mete un paso de construcción (build), sería usar una herramienta tipo Middleman que ya tenga un mecanismo para manejar localización (https://middlemanapp.com/advanced/localization/)

.....

De esto no se que vean más apropiado o si tienen otra idea?

**Comment by GregMBS** [comment]
O puedo generar un backend Laravel/MySQL, con los datos en 2 tablas
(español y ingles).

Greg

**Comment by bhserna** [comment]
El problema que yo veo es que ahorita el sitio es estático y utiliza Github Pages como hosting. Creo que lo ideal sería encontrar una forma que no requiera un backend e introduzca las menores decisiones lenguajes/frameworks posibles. Pero es solo mi opinion.

**Comment by GregMBS** [comment]
Puedo obtener un droplet Ubuntu en DigitalOcean. Ya tengo un plugin para un
panel adminitrativo para Laravel. Por eso, podemos editar la lista por una
manera fácil y segura.

Greg

**Comment by GregMBS** [comment]
Alternativamente, puedo hacerlo en puro PHP/MySQL sin framework, pero va a
tardar más.

On Sep 20, 2017 09:44, "Gregory Miles Blumenthal Scharf" <
llameadrpc@gmail.com> wrote:

Puedo obtener un droplet Ubuntu en DigitalOcean. Ya tengo un plugin para un
panel adminitrativo para Laravel. Por eso, podemos editar la lista por una
manera fácil y segura.

Greg

**Comment by CronGM** [comment]
**EDIT**: Voy a ver si lo puedo portar a simple JS de manera sencilla.

Si se implementa Angular, ya tengo una prueba de concepto sencilla armada, y que no require backend. Algo así:
```
//JS
var langDefs = {
  es: {
    hola: "Hola",
    prueba: "Prueba"
  },
  en: {
    hola: "Hello",
    prueba: "Test"
  },
  jp: {
    hola: "Ohaiyo",
    prueba: "Testo"
  }
},
$scope.text = langDefs[defaultLang];

$scopechooseLang = function chooseLang(chosenLang) {
  $scope.text = langDefs[chosenLang];
}

// VISTA
<p>Hola: {{ text.hola }}</p>
<p>Prueba: {{ text.prueba }}</p>
<label for="es"><input id="es" type="radio" ng-model="radio" value="es" ng-change="chooseLang(radio)">Español</label>
<label for="en"><input id="en" type="radio" ng-model="radio" value="en" ng-change="chooseLang(radio)">Inglés</label>
<label for="jp"><input id="jp" type="radio" ng-model="radio" value="jp" ng-change="chooseLang(radio)">Japonés</label>
```

**Comment by eldelentes** [comment]
Importante, por ahora creo que lo ideal no es agregar una traducción a todo el sitio

Cree una página llamada `world.html` necesito ayuda con eso pueden ver el siguiente issue #59
