### ISSUE TITLE
Iconos de categoría.

### ISSUE THREAD

**Issue by medinnna** [eldelentes/comoayudarmx#43]
Como las cards ya no son manuales, el icono de categoría para todas es iguales. Yo recomendaría establecer una lista de categorías definitivas que consideremos que puedan cubrir cualquier tipo de card y hacer una condición en el each donde dependiendo del type que tenga la card, le ponga la clase que necesita. ¿Cómo ven?

**Comment by eldelentes** [comment]
Estoy de acuerdo con eso, por ahora agregue uno génerico, vámos a ver que tan tardado es ir migrando esto a algo más solido, si no mañana podemos categorizar esto de mejor manera (Incluso con un color coding)...

**Comment by PatoBeltran** [comment]
Estoy de acuerdo, ya que el backend quede podriamos hacer que el icono venga desde el servidor dependiendo del tipo de card

**Comment by javierivero** [comment]
Estuve puliendo las categorías para hacerlas un poco más homogéneas, pero veo que algunos métodos pueden tener más de una categoría, saben como se refljea esto en código? Ejemplo "Type:categoria1 , type:categoria2"

**Comment by hectorbenitez** [comment]
@javierivero 
```
type: ["categoria1", "categoria2"]
```

prueba con las que dicen cosas como `Víveres/Varios`, se corregiran los filtros automaticamente

**Comment by JPIglesias-Triangle** [comment]
@eldelentes Podemos marcar cómo categorías: Víveres, Monetaria, Albergue, Acopio, Otros

No se que más se les ocurra

**Comment by digenz** [comment]
que tal : 
Víveres
Monetaria
Albergues
Centros de Acopio
Voluntarios
Medicamentos

**Comment by balamcan** [comment]
ya vi que es con font awesome, en una chanzita lo destripo y les pongo los iconitos por cada categoria, y tambien para ver si les puedo poner el codigo de colores que tambien mencionan en los comentarios

**Comment by medinnna** [comment]
Yo creo que la categoría de "Otros" o "Varios" no tiene caso ahora que podemos multiples categorías, además lo importante es que se simplifiquen y principalmente que todos estemos de acuerdo para que futuras cards tengan las categoría establecida y evitar duplicados por cuestión de acentos o algo parecido.

Basándome en las propuestas de @digenz, @JPIglesias-Triangle y el sitio actual creo que la lista podría ser:

1. Víveres
2. Monetaria
3. Albergues
4. Voluntarios
5. Equipo médico/Medicamentos
6. Limpieza/Aseo personal
7. Equipo de rescate
8. Asesoría profesional
9. Sangre
10. Veterinario
11. Transporte
12. Ropa

Creo que esto cubre bastante bien todas las categorías necesarias y evita duplicado y generalización y pues debemos sacarle a provecho a que se pueden aplicar multiples categorías.

Díganme si están de acuerdo con esto y empiezo a cambiarlo en las cards actuales, o si creen que debería haber alguna otra o quitar, o cambiar el nombre, etc.

**Comment by digenz** [comment]
De acuerdo,  me parece bien las categorías

**Comment by balamcan** [comment]
Suena bien las categorias, entonces en base a esas categorias yo me pongo a trabajar interprentandolo en los iconos correspondientes

**Comment by balamcan** [comment]
ya lo tengo con los iconos, como le hago push?

**Comment by medinnna** [comment]
La mejor forma es hacer fork del proyecto, trabajarlo, hacer push y después hacer un pull request para que @eldelentes lo revise en caso de conflictos.

**Comment by balamcan** [comment]
listo, gracias por indicarme como, ya hice el pull request para este issue que se resuelva

**Comment by javierivero** [comment]
Podrían darle un padding-right a los íconos? Se ven muy pegados a los textos
