### ISSUE TITLE
Agregar canal de comunicación

### ISSUE THREAD

**Issue by amorino** [eldelentes/comoayudarmx#55]
Qué tal, 

Entiendo que todos queremos ayudar, pero hacerlo de forma desorganizada hará que se trabaje doble y cada quién usando el stack que quiera. Creo que lo mejor es abrir un canal de comunicación y organizarnos. Por el momento cree un canal de Slack.com para podernos de acuerdo y por favor quien sea el encargado de mandar a producción (@eldelentes), principalmente, decirnos por donde empezar:

https://join.slack.com/t/comoayudarmx/shared_invite/enQtMjQzNTcyNjc1NzEzLTVmMTQ3MWQ0YTBkMjc0NmQwZWZlNzU1NmRmODRhNGNmYzQ3ZTU1NTQyZTZiMGMyNjU4YjI1MTQwMTdhNTQ5N2Q

Muchos saludos.

**Comment by eldelentes** [comment]
Perfecto @amorino es una gran idea.

¿Me ayudas agregando esta información al Readme?

**Comment by lmauromb** [comment]
Oigan para no dobletear esfuerzos podriamos unir fuerzas con los chicos de **CodeandoMexico**

Ellos ya cuentan con: 
- Un [Slack](codeandomexico.slack.com)
- Un [sitio](https://codeandomexico.github.io/terremoto-cdmx/) por ahora enfocado en cdmx pero con información relevante
- Un [Trello](https://trello.com/b/Vz4c8cbq/terremoto-cdmx) para operaciones

**Comment by IsabelPalomar** [comment]
Estoy de acuerdo con @lmauromb

**Comment by elbaloo** [comment]
@eldelentes se fueron a otro lado? ese link no jala.

**Comment by juanjodarko** [comment]
si, ya no sirve, se movieron a otro lugar?

**Comment by aalkz** [comment]
¿En dónde quedó el slack entonces? D:

**Comment by arturojain** [comment]
¿dónde se está llevando la comunicación?

**Comment by amorino** [comment]
[Nuevo link, aquí.](https://join.slack.com/t/comoayudarmx/shared_invite/enQtMjQ0NjA4OTgzMTg5LWZlZTI0ODNhYWJjMDdjZjQ3ODk5MjdhMjYwNzllYzhhOWI5MGI4MTAyNjljZWZhODYwODA0YTUzYTQ2MGMzOWI)

**Comment by miguejs** [comment]
Por el momento vamos a cerrar el canal de comunicacion, debido a que ya contamos con suficiente gente en el team de slack, pero si quieren aportar pueden seguir haciendolo mediante issues .
