### ISSUE TITLE
Traducir world.html

### ISSUE THREAD

**Issue by eldelentes** [eldelentes/comoayudarmx#59]
Para las personas en el extranjero hemos creado una página `world.html`para solo mostrar donaciones monetarias.

Necesito ayuda con:

- Traducir Meta Tags
- Traducir Texto de Modales
- Mostrar solamente las tarjetas con type "monetario"
- Traducir textos y botones de la card.

**Comment by bhserna** [comment]
Vale... yo ayudo con mostrar solo las tarjetas de tipo "monetario"

**Comment by GregMBS** [comment]
Puedo traducir a Inglés, si otros juegen con Javascript.

**Comment by reegoram** [comment]
¿Alguien esta traduciendo el texto del modal? Puedo ayudar con eso

**Comment by GregMBS** [comment]
Yo puedo. Inglés nativo.

**Comment by bhserna** [comment]
@eldelentes  Para que se muestren las tarjetas hay que poner el id "#cards_container"

**Comment by eldelentes** [comment]
@bhserna No me aparecen, ¿Tengo que tener el markup de la tarjeta en el world.html?

**Comment by bhserna** [comment]
sí.. también se necesita el template

**Comment by bhserna** [comment]
@eldelentes ahora te falta incluir el archivo cards.js antes del app.js en el world.html

**Comment by eldelentes** [comment]
@bhserna Creo que hay algo que me falta todavía 🤔

**Comment by bhserna** [comment]
@eldelentes se me hace que es que el id en el html esta como "#cards_container"... debe ser sin el `#`

**Comment by GregMBS** [comment]
Debo completar traducción de world.html en unos momentos.

Greg

**Comment by eldelentes** [comment]
@bhserna Jajaja listo, lo que hace el no dormir bien...

**Comment by novohispano** [comment]
@eldelentes que más necesitan para este tema?

**Comment by novohispano** [comment]
@GregMBS Do you need help translating anything?

**Comment by eldelentes** [comment]
@novohispano Literalmente la traducción de todo lo que existe en español en `world.html`solo no sé el estatus de @GregMBS

**Comment by GregMBS** [comment]
GregMBS/como ayudarme branch gmbs

**Comment by eldelentes** [comment]
Necesitamos una forma de cambiar la categoría de "Monetario" a "Money"...

**Comment by GregMBS** [comment]
Use "$". Mismísimo en México y EEUU.

Greg

**Comment by bhserna** [comment]
@eldelentes ahorita te ayudo con eso de "Monetaria"

**Comment by dino-at-thegovlab** [comment]
¡Hola! ¿Cómo puedo apoyar con traducciones?

**Comment by dino-at-thegovlab** [comment]
@eldelentes ¿te ayudo a traducir toda la página?

**Comment by mattdark** [comment]
@eldelentes Hola, ¿hay algo más que se necesite traducir? Puedo ayudar

**Comment by IsabelPalomar** [comment]
I'm back! En que puedo ayudar?

**Comment by reegoram** [comment]
Opino que se pueden traducir las cards que aparecen en world, porque la información todavía se renderea en español.

**Comment by GregMBS** [comment]
Crear versiones en ingles de los que deben aparecer en world.html y use
la categoría MONEY.

Greg

**Comment by eldelentes** [comment]
Por ahora solo esta el tema de las tarjetas, por favor ver #98
