### ISSUE TITLE
Multicategorías

### ISSUE THREAD

**Issue by javierivero** [eldelentes/comoayudarmx#65]
Alguien podría habilitar una opción para uqe un "Card" tenga más de una categoría?

**Comment by PatoBeltran** [comment]
Podriamos manejarlo como hastags o algo asi, pero como se veria en el frontend?

**Comment by hectorbenitez** [comment]
Podemos hacer que el json de cards funcione con string o array de strings para no romper las cards existentes.

Para el front end podemos como ul o simplemente separado por comas.

Ej: 
Tipo de donacion

-  Monetaria, Viveres

**Comment by bhserna** [comment]
Sí ... justo lo que dice @hectorbenitez creo que es lo más viable... y yo me iría a que este separado por comas.

**Comment by hectorbenitez** [comment]
@eldelentes puedo comenzar a trabajar en este issue desde ya

**Comment by bhserna** [comment]
yo digo que le des @hectorbenitez ... si te puedo ayudar en algo avísame.

**Comment by hectorbenitez** [comment]
PR #69, al final si lo manejo con elementos h3 porque los utlizamos para llenar los filtros

**Comment by bhserna** [comment]
@javierivero ya esta agregado lo de las multiples categorías... ahora para agregar múltiples categorías solo tienes que poner un arreglo en el atributo `type`

`{type: ["Monetaria", "Víveres"]}`
