### ISSUE TITLE
Filtro de todo el mundo juntos con algun tipo especifico no regresa resultados 

### ISSUE THREAD

**Issue by hectorbenitez** [eldelentes/comoayudarmx#71]
Si en el filtro de todo el mundo solo mostramos monetarios, podriamos resetear el filtro de type, o al menos mostrar un mensaje de que la mejor forma de ayudar desde fuera de Mexico es por medio de apoyos monetarios, para que la pagina no se quede solamente en blanco

**Comment by hectorbenitez** [comment]
@eldelentes 

Puedo ayudarte con este, reseteamos los filtros o agregamos un mensaje?

**Comment by bhserna** [comment]
@hectorbenitez no entiendo bien... pero creo que el problema aquí es que no se muestran por que simplemente no hay tarjetas con esas características. Creo que lo mejor sería mostrar un mensaje.

Talvez:

"No hay resultados para tu busqueda"

?

**Comment by hectorbenitez** [comment]
Suena bien, y suena sencillo por el momento, ahora lo resolvemos

**Comment by bhserna** [comment]
@hectorbenitez vas a trabajar en esto?

**Comment by hectorbenitez** [comment]
si, dejamelo a mi

**Comment by eldelentes** [comment]
@hectorbenitez ¿Ya quedo esto solucionado?

**Comment by hectorbenitez** [comment]
@eldelentes @bhserna 

Aqui esta un PR inicial
https://github.com/eldelentes/comoayudarmx/pull/123

**Comment by hectorbenitez** [comment]
<img width="902" alt="screen shot 2017-09-20 at 2 50 15 pm" src="https://user-images.githubusercontent.com/1191281/30664869-c6c93a3a-9e14-11e7-9e5b-f059fee57558.png">
