### ISSUE TITLE
voluntarios.html {Failed to load resource: net::ERR_TOO_MANY_REDIRECTS}

### ISSUE THREAD

**Issue by LockeAG** [eldelentes/comoayudarmx#76]
Probablemente la url del mapa dejo de existir, esta incorrecta o el dominio necesita ssl .

**Comment by javarv87** [comment]
Probablemente sea el https, lo estoy checando pero no me marca el error en consola que comentas

**Comment by LockeAG** [comment]
si ya lo veo bien de este lado !  gracias!
