### ISSUE TITLE
Implementar Fuentes "Verificadas"

### ISSUE THREAD

**Issue by javierivero** [eldelentes/comoayudarmx#79]
Equipo, necesitamos encontrar una manera de agregar un "badge" de si la fuente es verificada o no, podríamos encontrar una forma de hacer esta diferenciación en los cards?

**Comment by hectorbenitez** [comment]
Desde el punto de vista de desarrollo, podemos agregar el badge y en cards.js agregar una propiedad extra "verified": bool

Pero quien decide si esta o no verificada una carta?

**Comment by javierivero** [comment]
Yo, el gobierno de mexico me enviará una lista con las instituciones

**Comment by hectorbenitez** [comment]
Perfecto, ahora agrego un cambio con eso y tendras que modificar cards.js segun sea requerido, a las que no este verificadas no necesitas agregarles nada, solo a las que quieras validar

**Comment by javierivero** [comment]
Perfecto!

**Comment by bhserna** [comment]
super!

**Comment by javierivero** [comment]
Hector me dejas saber cuando esté listo ya que el Gobierno de Mexico esta por compartir la lista de instituciones

**Comment by hectorbenitez** [comment]
@bhserna cuando puedas vamos platicando de este PR

https://github.com/eldelentes/comoayudarmx/pull/92

<img width="497" alt="screen shot 2017-09-20 at 12 48 46 pm" src="https://user-images.githubusercontent.com/1191281/30658995-22a214e8-9e02-11e7-8655-12b73cde6528.png">

**Comment by javierivero** [comment]
Ya tengo la lista oficial, podemos probar?

**Comment by hectorbenitez** [comment]
@javierivero una vez que se haga el deployment, este es un ejemplo de un registro verificado

```
{title: "Donación Topos", description: "Los Topos son una asociación de rescatistas independientes. Tu ayuda provee de los utensilios necesarios para el rescate de personas.", type: "Monetaria", location: "Global", link: "https://twitter.com/topos/status/908000616575680512", verified: true}
```

tienes que agregar la parte final `, verified: true`

**Comment by javierivero** [comment]
Perfecto, como hacemos ya el deployment?

**Comment by hectorbenitez** [comment]
@bhserna el style.min.css no tiene los cambios de style.css, por eso no se ve el badge en verde, creo que el color le da mas relevancia

Como hacen el minified?

**Comment by javierivero** [comment]
https://cssminifier.com/

**Comment by javierivero** [comment]
Podemos cambiar el texto a "Fuente Oficial" ? en vez de "Verificada"

**Comment by hectorbenitez** [comment]
@javierivero ya mande el cambio para que diga `Fuente Oficial`, @eldelentes @bhserna podrian checar esto?
