### ISSUE TITLE
links navbar inconsistentes

### ISSUE THREAD

**Issue by elbaloo** [eldelentes/comoayudarmx#86]
de pagina a pagina se pierden links
fix: homogeneizar links en cada pagina

**Comment by juliescript** [comment]
Yo puedo tomar este issue, para la página en inglés sólo traduzco el nombre de los links o lo dejo en el mismo modelo que hay actualmente?

**Comment by elbaloo** [comment]
gracias @julietacampos, ya realicé el cambio correspondiente

**Comment by elbaloo** [comment]
también agregué un cambio para que el link a la pagina en ingles sea visible en el sitio movil pues por ahora está oculto
