### ISSUE TITLE
Folders por localidad?

### ISSUE THREAD

**Issue by Gabbrdz** [eldelentes/comoayudarmx#93]
Quisiera crear un folder para mi estado (Coahuila) y poner ahi todos los centros de acopio y la forma de ayudar desde aca, aunque estemos lejos, queria saber si puedo, pa ir armando y recabando informacion.

**Comment by eldelentes** [comment]
Por ahorita puede ser un poco complicado, cierro este issue pero no se descarta.

**Comment by Gabbrdz** [comment]
ok, muchas gracias, vere igual si puedo ayudar en otros issues
