### ISSUE TITLE
contenido de tarjetas en ingles

### ISSUE THREAD

**Issue by elbaloo** [eldelentes/comoayudarmx#98]
- [ ] definir/agregar nueva propiedad para descripcion en ingles
- [ ] leer descripcion en ingles si esta disponible si el lector esta en world.html
- [ ] traducir tarjetas a ingles

**Comment by LockeAG** [comment]
Podemos generar un `cards_en.js` para las traducciones en lo que se define una propiedad ?

**Comment by elbaloo** [comment]
suena bien, el punto es poner la informacion a la mano cuanto antes

**Comment by LockeAG** [comment]
yo me encargo

**Comment by novohispano** [comment]
@elbaloo @LockeAG cómo ven separar `description` en `description_en` y `description_es`?

```javascript
{
title: "Acopio Playa del Carmen", 
description_es: "Centro de acopio en Playa del Carmen",
description_en: "Collection Center in Playa del Carmen",
type: "Víveres",
location: "Playa del Carmen", 
link: "https://twitter.com/delitogomx/status/910503792789086210"
}
```

**Comment by novohispano** [comment]
La otra es simplemente usar el `cards_en.js` y ya. Así nos ahorramos el tema de tener filtering dependiendo del idioma para ocultar categorías y demás.

**Comment by LockeAG** [comment]
Yo ahora estoy a la mitad de card_en.js, ya casi .

**Comment by marino334** [comment]
Sugiero separar "description" en "description_en" y "description_es", de la otra forma de tener 2 archivos es mas facil que se pierda la sincronozacion de cambios entre archivos e inclusive "perder" tarjetas. necesitan ayuda para traducir? Como vas @LockeAG ?

**Comment by LockeAG** [comment]
@marino334  estoy apunto de terminarlas y ok , unifico los archivos en uno , pero requeririamos tambien : 

title_es
title_en

description_es
description_en

Tal vez solo  : 

title
title_en

description
description_en

para tener fallbacks

**Comment by marino334** [comment]
voto por la 2da opcion, asi no hay que cambiar la logica de usar los nuevos tags (title_en, description_en) todavia y es backward compatible, como dices puede ser fallback a title y description que estaran en espaniol

**Comment by LockeAG** [comment]
Uff saben que me acabo de dar cuenta , type_en seria necesario

**Comment by elbaloo** [comment]
La mejor opcion seria una sola fuente claro. cards_en es para hacer disponible la informacion inmediatamente pero por lo que veo, ésta va aumentando bastante rapido

**Comment by novohispano** [comment]
@LockeAG Sí, tienes razón. Se necesita eso para localizar el sitio por completo.

**Comment by LockeAG** [comment]
#141

**Comment by marino334** [comment]
En que quedo' localizacion (ingles y demas)? @eldelentes 
Veo 2 PR abiertos para ingles y frances con sus respectivos Cards.js pero el resto del sitio usando languages.js y su version (world.html). Me interesa ayudar a traducir

**Comment by almeidatercero** [comment]
también me apunto si necesitan ayuda con traducción manual

**Comment by munick** [comment]
Hola, en primera solo queiro decir que estoy super impresionado con el repo y todo lo que se ha hecho. Padrisimo. 

En segunda, como no veo nada concreto aqui, tengo una sugerencia simple para el sistema de traducir las tarjetas:

1. Incluir las traducciones usando [data attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*), paresido a la forma que data-lang se esta usando en languages.js. Por ejemplo: `data-descripcion_en`, `data-titulo_en`. Los atributos pueden estar en el elemento de la tarjeta o igual pueden estar en cada elemento que debe ser traducido.
1. [loadLanguage](https://github.com/eldelentes/comoayudarmx/blob/master/languages.js#L95) en languages.js puede buscar la traduccion en el dom de cada tarjeta, y si lo encuentra lo cambia. Asi app.js y languages.js pueden seguir haciendo solo lo que les pertenece. 
1. Finalmente para evitar tener que usar `type_en` como filtro, `type` se puede usar para el `value` de los `option`  elementos, asi el contenido del elemento  puede cambiar sin afectar los filtros.

**Comment by miguejs** [comment]
Vamos a cambiar  la conversacion a este issue para que puedan formar un team y ver de que  forma pueden solucionar este problema #194
